// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ROvXD-yyeqIjnMW6bOeq-fXFPprR_D8',
    appId: '1:741136601618:web:49e1b9f55936febedbfecb',
    messagingSenderId: '741136601618',
    projectId: 'helena-95a1c',
    authDomain: 'helena-95a1c.firebaseapp.com',
    storageBucket: 'helena-95a1c.appspot.com',
    measurementId: 'G-421YH21NC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFTWRfpH9Gg3IkgH4ELu6luen48yz-Pac',
    appId: '1:741136601618:android:df9871376eefe168dbfecb',
    messagingSenderId: '741136601618',
    projectId: 'helena-95a1c',
    storageBucket: 'helena-95a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb65GuqNq_jWxs_OghbeARssVy3pPeBAg',
    appId: '1:741136601618:ios:52fbccce53c66900dbfecb',
    messagingSenderId: '741136601618',
    projectId: 'helena-95a1c',
    storageBucket: 'helena-95a1c.appspot.com',
    iosBundleId: 'com.example.helena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb65GuqNq_jWxs_OghbeARssVy3pPeBAg',
    appId: '1:741136601618:ios:2f3ae883e8d1b04cdbfecb',
    messagingSenderId: '741136601618',
    projectId: 'helena-95a1c',
    storageBucket: 'helena-95a1c.appspot.com',
    iosBundleId: 'com.example.helena.RunnerTests',
  );
}
